steel-dev/steel-browser

api/src/services/cdp.service.ts

* Allow for recordings to work when deployed and binded to 0.0.0.0

fix(recording): allow 0.0.0.0:3000 to be safely called without https

---

.gitattributes

There's an issue when running on windows where the repo gets cloned with CLRF line endings which makes the entrypoint.sh file not able to be found

Add gitattributes to ensure line endings are set to LF for all OSs

---

api/src/utils/browser.ts

Hello! I noticed that `app/src/utils/browser.ts` does not support "Program Files (x86)" directory.
I modified it to include checking Chrome installations in "Program Files (x86)" paths.

fix: add support for 'Program Files (x86)' path

---

.dockerignore
api/Dockerfile

I just noticed that Docker image for API builds a little bit longer than I expected, so I applied a few optimizations to speed consecutive builds.
1. Use RUN --mount to cache OS package files and metadata
2. Reorder instructions so changes in source code invalidate less build steps
3. Reduce number of resulting layers (there is a limit)
4. Eliminate some duplications (like `DISPLAY` env)

Optimize Dockerfile to reduce number of layers and speedup build

---

api/.env.example
api/src/env.ts
api/src/utils/browser.ts

This adds an environment variable that lets you use a custom chromium binary. For example, in `api/.env` if you have set
```env
CHROME_EXECUTABLE_PATH=/Users/QAComet/Library/Caches/ms-playwright/chromium-1148/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```
you will be using Playwright's default chromium build that's cached by NPM.

feat: add CHROME_EXECUTABLE_PATH environment variable for custom chromium binaries

---

api/src/modules/actions/actions.controller.ts
api/src/modules/actions/actions.routes.ts
api/src/modules/actions/actions.schema.ts
api/src/modules/sessions/sessions.controller.ts
api/src/modules/sessions/sessions.routes.ts
api/src/modules/sessions/sessions.schema.ts
api/src/services/cdp.service.ts
api/src/services/selenium.service.ts
api/src/services/session.service.ts
api/src/utils/proxy.ts

If proxyUrl was provided for a session, always use [proxy-chain](https://github.com/apify/proxy-chain) in front of the real proxy to meter data transferred via proxy.

Measure traffic usage if proxy server is specified

---

api/.env.example
api/src/utils/proxy.ts

This fixes issues with the recording extension not properly routing the events back to the API when using a custom proxy URL

fix: ensure requests made back to the API are not proxied

---

ui/src/App.tsx
ui/src/components/sessions/session-console/session-devtools.tsx
ui/src/components/sessions/session-console/session-logs.tsx
ui/src/components/sessions/session-viewer/session-viewer.tsx
ui/src/env.ts

Many people have faced issues with running steel-browser locally because the docs didn't mention to copy over env.local.example in the `./ui` folder
This removes the need to do that in the first place

fix: remove env requirement for local dev

---

api/src/services/cdp.service.ts

Fixes: https://github.com/steel-dev/steel-browser/issues/33
Chromium was crashing due to the combination of `--disable-gpu` and `--disable-software-rasterizer`. When GPU acceleration is disabled, Chrome falls back to software rendering (SwiftShader). However, `--disable-software-rasterizer` prevents this fallback, leaving no rendering option, causing a crash in different environments. Removing this flag ensures Chromium can properly render via software when GPU is disabled.

Fix Puppeteer Crash: Remove --disable-software-rasterizer

---

README.md
docker-compose.yml

I ran into issues while trying to run locally via Docker. I found this message [here ](https://discord.com/channels/1285696350117167226/1328008655764979773/1334540718483439759) helpful so I added a note in the Getting Started section about modifying environment variables to use localhost for local development. This helps developers avoid common connection issues when running the stack locally.
I also updated the network-name because docker pre-fixes it with the parent directory's name. This would be helpful for those who clone with custom aliases.

Docker Local Dev Host

---

api/entrypoint.sh

Fixes: [steel-dev/steel-browser#24](https://github.com/steel-dev/steel-browser/issues/24)
Running docker-compose up multiple times without --force-recreate results in Xvfb and DBus failing to start due to stale lock files.
- Failed to start message bus: The pid file "/run/dbus/pid" exists
- Fatal server error: Server is already active for display 10
- Missing X server or $DISPLAY
- Failed to connect to socket /run/dbus/system_bus_socket: Connection refused
- DBus and Xvfb do not clean up their lock files when Docker Compose restarts the container, leading to conflicts when trying to start them again.
- Lock files (/run/dbus/pid and /tmp/.X10-lock) persist inside mounted volumes (like .cache), even after containers are stopped.
- Entry point script does not clear these files before …

Fix Xvfb & DBus Startup Issues in Docker Compose

---

api/src/modules/sessions/sessions.controller.ts
api/src/modules/sessions/sessions.schema.ts
api/src/services/session.service.ts

An extra session restart call was causing launch times to nearly double -- refactored some of the session logic such that launching a new session doesn't duplicate the work

fix: remove extra session restart call and rename pending to idle

---

api/src/services/cdp.service.ts
api/src/services/session.service.ts
api/src/types/browser.ts

This pull request includes several changes to the `CDPService` and `SessionService` classes, as well as updates to the `BrowserLauncherOptions` interface. The main focus is on improving the handling of browser sessions, configuration, and cookie data.
* Removed the `isActive` property and replaced it with more detailed session state management, including `localStorageData`, `fingerprintData`, and `currentSessionConfig` reset on shutdown. [[1]](diffhunk://#diff-f92e758934f17be597c0b9471e00bc520dd55b111d99d2435355ca3d37a71a11L18-R18) [[2]](diffhunk://#diff-f92e758934f17be597c0b9471e00bc520dd55b111d99d2435355ca3d37a71a11L35-R35) [[3]](diffhunk://#diff-f92e758934f17be597c0b9471e00bc520dd55b111d99d2435355ca3d37a71a11L382-R386) [[4]](diffhunk://#diff-f92e758934f17be597c0b9471e00bc520dd55b111d99d …

feat: reuse idle browser when config is unchanged

---

api/Dockerfile
api/package.json
api/src/build-server.ts
api/src/modules/playground/playground.controller.ts
api/src/modules/playground/playground.routes.ts
api/src/routes.ts
ui/package-lock.json
ui/package.json
ui/public/serve.json
ui/src/App.tsx
ui/src/components/header/header.tsx
ui/src/components/playground/CodeEditor.tsx
ui/src/components/playground/LanguageSelector.tsx
ui/src/components/playground/PythonResult.tsx
ui/src/components/playground/TerminalComponent.tsx
ui/src/hooks/use-file-sync.ts
ui/src/hooks/use-web-container.ts
ui/src/index.css
ui/src/pages/home-page.tsx
ui/src/pages/playground-page.tsx
ui/src/root-layout.tsx
ui/src/types/language.ts
ui/src/utils/constants.ts
ui/vite.config.ts

Basic playground implementation with support for typescript and python code. 
This uses webcontainers to run typescript playground code, probably will want to move off that as it cannot access local endpoints.
also, a server hook has been added to embed the  #iframe as it wasn't working by default.
api/src/build-server.ts
```
server.addHook("onSend", (request, reply, payload, done) => {
reply.header("Cross-Origin-Resource-Policy", "cross-origin");
reply.header("Cross-Origin-Embedder-Policy", "require-corp");
done();
});
```

feat: Basic playground implementation (wip)

---

api/src/modules/sessions/sessions.controller.ts

This pull request includes a small but important change to the `api/src/modules/sessions/sessions.controller.ts` file. The change ensures that the `initialDimensions` field has a default value if it is not already set.
* [`api/src/modules/sessions/sessions.controller.ts`](diffhunk://#diff-fc5a20a5ff673a4dbb6e9d7fdebe599ebf36602bca4ebe5b20cdaea8faf3399cL168-R168): Updated the `initialDimensions` field to default to `{ width: 1920, height: 1080 }` if no dimensions are provided.

fix: bug when dimensions are undefined

---

api/Dockerfile
api/package.json
api/patcher/scripts/patcher.js
api/src/modules/sessions/sessions.controller.ts
api/src/services/session.service.ts
api/src/types/browser.ts
package-lock.json

This pull request includes several changes to the `api` package, primarily focusing on downgrading the `puppeteer-core` version and updating the usage of `CookieData` to `Protocol.Network.Cookie`. The most important changes are summarized below:
* [`api/package.json`](diffhunk://#diff-d0ab9c1cc78fba971b5270314ad877706d340d099b42f46a406fc5de6a32fdf0L50-R50): Downgraded `puppeteer-core` from version `24.2.0` to `23.6.0`.
* [`api/patcher/scripts/patcher.js`](diffhunk://#diff-0528fe9db37e9d10f356bf3a407f455744b880d3a64ff08ac82fca1a3b7691eaL73-R75): Updated the patch file path to use `23.6.x` for `puppeteer-core` instead of `22.13.x`.
* [`api/src/modules/sessions/sessions.controller.ts`](diffhunk://#diff-fc5a20a5ff673a4dbb6e9d7fdebe599ebf36602bca4ebe5b20cdaea8faf3399cR6): Imported `Protocol` …

fix: downgrade to puppeteer 23.6 for now

---

api/src/modules/sessions/sessions.controller.ts
api/src/plugins/schemas.ts

The service is configuring URLs with a port included in the domain: https://github.com/steel-dev/steel-browser/blob/c5ea013e03733b3c283fd9aa7941a258d55a9427/api/src/services/session.service.ts#L32...L35.  
However, this isn't consistent across other parts of the code, so I'm raising a fix for it.

Use correct URLs for session

---

api/src/env.ts
api/src/services/cdp.service.ts

This pull request includes changes to support configurable time zones in the `api` module. The most important changes include adding a new environment variable for the default time zone and updating the `CDPService` class to use this new variable.
Improvements to time zone configuration:
* [`api/src/env.ts`](diffhunk://#diff-08db4c2c874e5cb71cb4b6caf511f45f26a590a4592fd6d2ebb2a1f0d580a5f3R39): Added `DEFAULT_TIMEZONE` as an optional string in the environment schema.
* [`api/src/services/cdp.service.ts`](diffhunk://#diff-f92e758934f17be597c0b9471e00bc520dd55b111d99d2435355ca3d37a71a11L43-R43): Modified the `CDPService` class to use the `DEFAULT_TIMEZONE` environment variable, falling back to the system's time zone if not set.

fix: allow overriding default tz

---

.husky/commit-msg
api/Dockerfile
api/entrypoint.sh
api/package.json
commitlint.config.js
package-lock.json
package.json
ui/Dockerfile

This pull request introduces commit message linting using `commitlint` and `husky`, and updates the `package.json` file to include the necessary dependencies and scripts.
Commit message linting setup:
* [`.husky/commit-msg`](diffhunk://#diff-292bac03df29207ee254ba91cfc30951b10c50c0a9fff3a0768778cebe5f4c4aR1): Added a command to run `commitlint` on commit messages.
* [`commitlint.config.js`](diffhunk://#diff-2b1ae4316086c0ebb213227790133a792300e1cef03b0afc067b23d3399ea5caR1-R3): Created a new configuration file for `commitlint` that extends the conventional configuration.
Updates to `package.json`:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L14-R28): Added `husky` to the `prepare` script and included `@commitlint/cli`, …

feat: add commitlint

---

api/src/env.ts
api/src/modules/sessions/sessions.controller.ts
api/src/services/file.service.ts

* [`api/src/env.ts`](diffhunk://#diff-08db4c2c874e5cb71cb4b6caf511f45f26a590a4592fd6d2ebb2a1f0d580a5f3R7): Added default value for `NODE_ENV` to ensure it defaults to "development" if not specified.
* [`api/src/modules/sessions/sessions.controller.ts`](diffhunk://#diff-fc5a20a5ff673a4dbb6e9d7fdebe599ebf36602bca4ebe5b20cdaea8faf3399cL4-R4): Added `SessionDetails` import and updated session details to include `proxyTxBytes` and `proxyRxBytes` fields. [[1]](diffhunk://#diff-fc5a20a5ff673a4dbb6e9d7fdebe599ebf36602bca4ebe5b20cdaea8faf3399cL4-R4) [[2]](diffhunk://#diff-fc5a20a5ff673a4dbb6e9d7fdebe599ebf36602bca4ebe5b20cdaea8faf3399cR94-R97)
* [`api/src/services/file.service.ts`](diffhunk://#diff-46509af95f64e20d45abb962580f0978ab6000a9fea6881deb13ea362ae402aeR9): Refactored to use the `env` …

fix: error with session details

---

api/src/utils/proxy.ts
docker-compose.yml

This pull request includes changes to the `ProxyServer` class in `api/src/utils/proxy.ts` and updates to the `docker-compose.yml` file. The most important changes focus on managing host connections and updating the Docker configuration.
Enhancements to `ProxyServer`:
* Introduced a `hostConnections` set to track connection IDs in the `ProxyServer` class.
* Updated the `prepareRequestFunction` to add `connectionId` to the `hostConnections` set when the hostname matches the environment host.
* Modified the `connectionClosed` event handler to check if the `connectionId` is in the `hostConnections` set before updating byte statistics and to remove the `connectionId` from the set.
Docker configuration updates:
* Changed the port mapping for the `ui` service in `docker-compose.yml` from …

fix: dont calculate proxy usage on internal calls

---

api/src/env.ts
api/src/services/session.service.ts

Updated env.ts to show CHROME_ARGS env variable and spreads CHROME_ARGS into browser launch args

feat: added ability to pass chrome args to new sessions via .env or docker-compose

---

api/package.json
api/src/plugins/browser-session.ts
api/src/services/cdp/cdp.service.ts

This pull request removes the `fastify-graceful-shutdown` dependency and replaces its functionality with a custom implementation in the `CDPService` class. Additionally, it introduces a timeout mechanism for browser launches and includes minor formatting updates.
* Removed the `fastify-graceful-shutdown` package from `api/package.json` and its import from `api/src/plugins/browser-session.ts`. [[1]](diffhunk://#diff-d0ab9c1cc78fba971b5270314ad877706d340d099b42f46a406fc5de6a32fdf0L55) [[2]](diffhunk://#diff-b4dbad64e9719420374f56d879f450d59e06b4f1178e9c4349f7a70fcc7685b5L1-L5)
* Deleted the graceful shutdown logic from `browserSessionPlugin`, including signal listeners and session cleanup logic.
* Introduced a timeout mechanism for browser launches to ensure the process fails gracefully if …

fix: remove graceful shutdown

---

api/src/plugins/schemas.ts

Resolves a build issue for type mismatch

Hotfix: scalar fastify plugin still uses v4

---

api/src/modules/sessions/sessions.controller.ts
api/src/modules/sessions/sessions.schema.ts
api/src/services/cdp-lifecycle.service.ts
api/src/services/cdp/cdp.service.ts
api/src/services/session.service.ts
api/src/types/browser.ts

Removes the legacy life cycle hooks and adds a new `credentials` option to the sessions API.

Add credentials option to create session

---

api/src/env.ts
api/src/services/cdp/cdp.service.ts

`DEBUG_CHROME_PROCESS` introduced to control whether Chrome process stdout and stderr are enabled.
* Added a new optional environment variable, `DEBUG_CHROME_PROCESS`, to the `envSchema` in `api/src/env.ts`. This variable is transformed to a boolean and defaults to `"false"`.
* Updated the `dumpio` property in the Chrome launch options to use the new `DEBUG_CHROME_PROCESS` environment variable, allowing dynamic control of Chrome process logging.

fix: make chrome debugging optional with env var

---

api/package.json
api/src/services/cdp/cdp.service.ts
api/src/telemetry/noop.ts
api/src/telemetry/tracer.ts
api/tsconfig.json
package-lock.json

This adds the OpenTelemetry's API as an optional dependency, if enabled and your server has the appropriate instrumentation you can collect the additional spans associated with the CDP service. Includes necessary helpers for creating new spans.

Add OpenTelemetry API to CDP Services

---

api/src/services/cdp/utils/validation.ts

This pull request includes a minor update to the `validation.ts` file. It removes the unused `ResourceError` import and updates the import path for `launch-errors` to include the `.js` file extension.

fix: esm import error causing build issue

---

api/src/services/cdp/cdp.service.ts
api/src/services/cdp/plugins/core/base-plugin.ts
api/src/services/cdp/plugins/core/plugin-manager.ts

Extends the plugin manager to add a `onSessionEnd` hook which gets called when the session gets ended externally or the connection disconnects. This is different to the `onShutdown` as this can get called during the cleanup phase when starting a new session

feat: add onSessionEnd hook to plugin manager

---

api/src/services/cdp/cdp.service.ts
api/src/services/cdp/utils/validation.ts
api/src/services/context/chrome-context.service.ts
api/src/services/session.service.ts
api/src/services/timezone-fetcher.service.ts
api/src/types/browser.ts
api/src/utils/extensions.ts

It introduces a `TimezoneFetcher` service that gets the timezone from a proxy's IP without blocking other startup tasks. To improve speed and reliability, it queries multiple APIs concurrently and includes a timeout. Other I/O operations were also made asynchronous to further improve performance

perf: run timezone fetching in background

---

api/package.json
api/src/modules/sessions/sessions.routes.ts
api/src/services/cdp/cdp.service.ts
api/src/utils/passthough-proxy.ts
api/src/utils/proxy.ts
package-lock.json

There's an issue with how proxy-chain's direct requests handle `transfer-encoding=chunked` requests where the headers/body become malformed. 
This bypasses these issues by providing a simple reverse proxy for `CONNECT` commands and performs the request inline for each following request after the connection has been established.

Fix: Session recording bug when using proxies

---

api/src/modules/actions/actions.controller.ts

This PR resolves a `ReferenceError: __name is not defined` that occurs when running Puppeteer operations in an environment that uses `esbuild` for transpilation, such as `tsx` or Vitest.
When using `tsx`, `esbuild` transpiles named function expressions to use a `__name` helper function to preserve the function's `.name` property. For example:
```javascript
// Original code
function myFunc() {}
// Transpiled by esbuild
var myFunc = __name(function() {}, "myFunc");
```
When Puppeteer's `page.evaluate()` executes this transpiled code in the browser, the `__name` helper function does not exist in the `window` scope, causing a fatal `ReferenceError`. This affects not only our own evaluation strings but also Puppeteer's internal helper functions that get serialized and executed in the browser. …

fix: Polyfill `__name` to prevent esbuild errors in Puppeteer context
